#!/bin/bash

# HOSTNAME = network name
echo -e ${col1_font_code}${col1_bg_code}"HOSTNAME" ${reset} "=" ${col2_font_code}${col2_bg_code}$HOSTNAME${reset};
# TIMEZONE = time zone as: America/New_York UTC -5 (time zone must be taken from the system and be correct for the current location)
echo -e ${col1_font_code}${col1_bg_code}"TIMEZONE" ${reset} "=" ${col2_font_code}${col2_bg_code}$TIMEZONE${reset};
# USER = current user who ran the script
echo -e ${col1_font_code}${col1_bg_code}"USER" ${reset} "=" ${col2_font_code}${col2_bg_code}$USER${reset};
# OS = type and version of operating system
echo -e ${col1_font_code}${col1_bg_code}"OS" ${reset} "=" ${col2_font_code}${col2_bg_code}$OSVER $OSNAME${reset};
# DATE = current time as: 12 May 2020 12:24:36
echo -e ${col1_font_code}${col1_bg_code}"DATE" ${reset} "=" ${col2_font_code}${col2_bg_code}$DATE${reset};
# UPTIME = system uptime
echo -e ${col1_font_code}${col1_bg_code}"UPTIME" ${reset} "=" ${col2_font_code}${col2_bg_code}$UPTIME${reset};
# UPTIME_SEC = system uptime in seconds
echo -e ${col1_font_code}${col1_bg_code}"UPTIME_SEC" ${reset} "=" ${col2_font_code}${col2_bg_code}$UPTIME_SEC${reset};
# IP = _ip address of the machine on any of the network interfaces
echo -e ${col1_font_code}${col1_bg_code}"IP" ${reset} "=" ${col2_font_code}${col2_bg_code}$IP${reset};
# MASK = network mask of any of the network interfaces as: xxx.xxx.xxx.xxx.
echo -e ${col1_font_code}${col1_bg_code}"MASK" ${reset} "=" ${col2_font_code}${col2_bg_code}$MASK${reset};
# GATEWAY = default gateway ip
echo -e ${col1_font_code}${col1_bg_code}"GATEWAY" ${reset} "=" ${col2_font_code}${col2_bg_code}$GATEWAY${reset};
# RAM_TOTAL = main memory size in GB with an accuracy of three decimal places as: 3.125 GB
echo -e ${col1_font_code}${col1_bg_code}"RAM_TOTAL" ${reset} "=" ${col2_font_code}${col2_bg_code}$RAM_TOTAL "GB"${reset};
# RAM_USED = used memory size in GB with an accuracy of three decimal places
echo -e ${col1_font_code}${col1_bg_code}"RAM_USED" ${reset} "=" ${col2_font_code}${col2_bg_code}$RAM_USED "GB"${reset};
# RAM_FREE = free memory size in GB, with an accuracy of three decimal places
echo -e ${col1_font_code}${col1_bg_code}"RAM_FREE" ${reset} "=" ${col2_font_code}${col2_bg_code}$RAM_FREE "GB"${reset};
# SPACE_ROOT = root partition size in MB, with an accuracy of two decimal places, as 254.25 MB
echo -e ${col1_font_code}${col1_bg_code}"SPACE_ROOT" ${reset} "=" ${col2_font_code}${col2_bg_code}$SPACE_ROOT "MB"${reset};
# SPACE_ROOT_USED = size of used space of the root partition in MB, with an accuracy of two decimal places
echo -e ${col1_font_code}${col1_bg_code}"SPACE_ROOT_USED" ${reset} "=" ${col2_font_code}${col2_bg_code}$SPACE_ROOT_USED "MB"${reset};
# SPACE_ROOT_FREE = size of free space of the root partition in MB, with an accuracy of two decimal places
echo -e ${col1_font_code}${col1_bg_code}"SPACE_ROOT_FREE" ${reset} "=" ${col2_font_code}${col2_bg_code}$SPACE_ROOT_FREE "MB"${reset};